/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const LEDPreset = IDL.Record({
  'color' : IDL.Text,
  'brightness' : IDL.Nat,
});
export const Pattern = IDL.Record({
  'thumbnail' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Time,
  'gCode' : IDL.Text,
  'ledPresets' : IDL.Opt(LEDPreset),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPattern' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'deletePattern' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPattern' : IDL.Func([IDL.Text], [Pattern], ['query']),
  'getPatternCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
  'patternExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'savePattern' : IDL.Func([Pattern], [], []),
  'updatePatternLEDs' : IDL.Func([IDL.Text, LEDPreset], [], []),
  'updatePatternThumbnail' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const LEDPreset = IDL.Record({ 'color' : IDL.Text, 'brightness' : IDL.Nat });
  const Pattern = IDL.Record({
    'thumbnail' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Time,
    'gCode' : IDL.Text,
    'ledPresets' : IDL.Opt(LEDPreset),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPattern' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'deletePattern' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPattern' : IDL.Func([IDL.Text], [Pattern], ['query']),
    'getPatternCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPatterns' : IDL.Func([], [IDL.Vec(Pattern)], ['query']),
    'patternExists' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'savePattern' : IDL.Func([Pattern], [], []),
    'updatePatternLEDs' : IDL.Func([IDL.Text, LEDPreset], [], []),
    'updatePatternThumbnail' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };