/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LEDPreset { 'color' : string, 'brightness' : bigint }
export interface Pattern {
  'thumbnail' : [] | [string],
  'name' : string,
  'createdAt' : Time,
  'gCode' : string,
  'ledPresets' : [] | [LEDPreset],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPattern' : ActorMethod<[string, string], undefined>,
  'deletePattern' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPattern' : ActorMethod<[string], Pattern>,
  'getPatternCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listPatterns' : ActorMethod<[], Array<Pattern>>,
  'patternExists' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'savePattern' : ActorMethod<[Pattern], undefined>,
  'updatePatternLEDs' : ActorMethod<[string, LEDPreset], undefined>,
  'updatePatternThumbnail' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];